In [1]:
import syft as sy
import numpy as np
from syft.core.adp.data_subject import DataSubject

/Users/fizahusain/x86-64/miniforge_x86_64/envs/syft/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
from syft.core.adp.data_subject_ledger import DataSubjectLedger
from syft.core.adp.ledger_store import DictLedgerStore
from typing import Any

ledger_store = DictLedgerStore()
user_key = b"1231"
ledger = DataSubjectLedger.get_or_create(store=ledger_store, user_key=user_key)

def get_budget_for_user(*args: Any, **kwargs: Any) -> float:
    return 999999

def deduct_epsilon_for_user(*args: Any, **kwargs: Any) -> bool:
    return True

Creating new Ledger


In [3]:
test = DataSubject(name="Test")
test2 = DataSubject(name="Test2")

In [4]:
from syft.core.tensor.autodp.phi_tensor import PhiTensor

In [5]:
# 8-bit integers
L = -128
U = 127

In [6]:
n = 5

In [84]:
tensor1 = PhiTensor(np.ones(n, dtype=np.int8), min_vals=1, max_vals=1, data_subjects= [test] * n)
tensor2 = PhiTensor(U*np.ones(n, dtype=np.int8), min_vals=U, max_vals=U, data_subjects= [test2] * n)

In [80]:
tensor_sum = tensor1 + tensor2

In [82]:
tensor_sum.dtype

dtype('int64')

In [77]:
result_sum = tensor_sum.publish(get_budget_for_user=get_budget_for_user,
                                deduct_epsilon_for_user=deduct_epsilon_for_user,
                                ledger=ledger,
                                sigma=1
                                )

100%|██████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 202.37it/s]

Epsilon spend  [nan nan nan nan nan]
Highest possible spend  nan
Epsilon spend  [nan nan nan nan nan]
Highest possible spend  nan
We have filtered all the input tensors. Now to compute the result:
Filtered inputs  [array([65536, 65536, 65536, 65536, 65536]), array([-65536, -65536, -65536, -65536, -65536])]
original output (before noise: [0. 0. 0. 0. 0.]
noise:  [-0.04644206  0.13472507 -1.13558716  0.25197183 -0.49519187]
got output <class 'numpy.ndarray'> float64


In [78]:
result_sum

array([-0.04644206,  0.13472507, -1.13558716,  0.25197183, -0.49519187])

In [99]:
tensor1 = PhiTensor(np.ones(n, dtype=np.int8), min_vals=1, max_vals=1, data_subjects= [test] * n)
tensor2 = PhiTensor(U*np.ones(n, dtype=np.int8), min_vals=U, max_vals=U, data_subjects= [test2] * n)
tensor_sum = tensor1 + tensor2

In [100]:
tensor_sum.dtype

dtype('int64')

In [101]:
result_sum = tensor_sum.publish(get_budget_for_user=get_budget_for_user,
                                deduct_epsilon_for_user=deduct_epsilon_for_user,
                                ledger=ledger,
                                sigma=1
                                )

100%|██████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 201.72it/s]

Epsilon spend  [nan nan nan nan nan]
Highest possible spend  nan
Epsilon spend  [nan nan nan nan nan]
Highest possible spend  nan
We have filtered all the input tensors. Now to compute the result:
Filtered inputs  [array([65536, 65536, 65536, 65536, 65536]), array([-65536, -65536, -65536, -65536, -65536])]
original output (before noise: [0. 0. 0. 0. 0.]
noise:  [-0.83394128 -0.76187168  0.9130962  -0.343097    0.99359776]
got output <class 'numpy.ndarray'> float64


In [102]:
result_sum

array([-0.83394128, -0.76187168,  0.9130962 , -0.343097  ,  0.99359776])

In [185]:
# 64-bit integers
L = -(2**63)
U = 2**63 - 1

In [187]:
n = 5

In [188]:
np.iinfo(np.dtype('int64')).max

9223372036854775807

In [189]:
tensor1 = PhiTensor(np.ones(n, dtype=np.int64), min_vals=1, max_vals=1, data_subjects=[test] * n)
tensor2 = PhiTensor(np.full(n, U, dtype=np.int64), min_vals=U, max_vals=U, data_subjects=[test] * n)
tensor_sum = tensor1 + tensor2

In [193]:
tensor_sum

PhiTensor(child=FixedPrecisionTensor(child=[0 0 0 0 0]), min_vals=<lazyrepeatarray data: -9223372036854775808 -> shape: (5,)>, max_vals=<lazyrepeatarray data: -9223372036854775808 -> shape: (5,)>)

In [194]:
result_sum = tensor_sum.publish(get_budget_for_user=get_budget_for_user,
                                deduct_epsilon_for_user=deduct_epsilon_for_user,
                                ledger=ledger,
                                sigma=1
                                )

PUBLISHING TO GAMMA:
FixedPrecisionTensor(child=[0 0 0 0 0])


100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.06it/s]

Epsilon spend  [696219.831434 696219.831434 696219.831434 696219.831434 696219.831434]
Highest possible spend  696219.8314340019
Attemping to spend epsilon: 696219.8314340019. Try: 0
got user budget 999999.0 epsilon_spent 696219.8314340019
We have filtered all the input tensors. Now to compute the result:
Filtered inputs  [array([0, 0, 0, 0, 0])]
original output (before noise: [[0 0 0 0 0]]
noise:  [[-0.11098883 -0.30177045  1.2468398   0.37408938 -0.52528706]]
Noise after FPT [[ -7273 -19776  81712  24516 -34425]]
got output <class 'numpy.ndarray'> int64
Final FPT Values FixedPrecisionTensor(child=[ -7273 -19776  81712  24516 -34425])


In [195]:
result_sum

FixedPrecisionTensor(child=[ -7273 -19776  81712  24516 -34425])

The above overflow can be prevented if the lenght of the dataset ($u$) is known to the data analyst. The direct check is that the blow up cannot occur if:
$maxVal * len(u) \leq U$ \
$minVal * len(u) \geq L$

The above method won't work for the floating-point arithmetic due to rounding effect.

In [198]:
tensor1 = PhiTensor(np.ones(n, dtype=np.float64), min_vals=1, max_vals=1, data_subjects=[test] * n)
tensor2 = PhiTensor(np.full(n, U - 1, dtype=np.float64), min_vals=U-1, max_vals=U-1, data_subjects=[test] * n)
tensor_sum = tensor1 + tensor2

In [199]:
tensor_sum

PhiTensor(child=FixedPrecisionTensor(child=[-9223372036854710272 -9223372036854710272 -9223372036854710272
 -9223372036854710272 -9223372036854710272]), min_vals=<lazyrepeatarray data: 9223372036854775807 -> shape: (5,)>, max_vals=<lazyrepeatarray data: 9223372036854775807 -> shape: (5,)>)

In [200]:
result_sum = tensor_sum.publish(get_budget_for_user=get_budget_for_user,
                                deduct_epsilon_for_user=deduct_epsilon_for_user,
                                ledger=ledger,
                                sigma=1
                                )

PUBLISHING TO GAMMA:
FixedPrecisionTensor(child=[-9223372036854710272 -9223372036854710272 -9223372036854710272
 -9223372036854710272 -9223372036854710272])


100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 85.24it/s]

Epsilon spend  [nan nan nan nan nan]
Highest possible spend  nan
We have filtered all the input tensors. Now to compute the result:
Filtered inputs  [array([-9223372036854710272, -9223372036854710272, -9223372036854710272,
       -9223372036854710272, -9223372036854710272])]
original output (before noise: [[-9223372036854710272 -9223372036854710272 -9223372036854710272
  -9223372036854710272 -9223372036854710272]]
noise:  [[-1.26746132  2.53592956 -0.51710111 -1.60698546 -0.56351634]]
Noise after FPT [[ -83064  166194  -33888 -105315  -36930]]
got output <class 'numpy.ndarray'> int64
Final FPT Values FixedPrecisionTensor(child=[ 9223372036854758280 -9223372036854544078 -9223372036854744160
  9223372036854736029 -9223372036854747202])


In [205]:
result_sum.decode()

array([ 1.40737488e+14, -1.40737488e+14, -1.40737488e+14,  1.40737488e+14,
       -1.40737488e+14])